// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC22xk19-g75PRJ-tBwbzKiU_rBnCzxJec',
    appId: '1:779586378999:web:4c67c2c19503ec96f787f2',
    messagingSenderId: '779586378999',
    projectId: 'fir-auth-14729',
    authDomain: 'fir-auth-14729.firebaseapp.com',
    storageBucket: 'fir-auth-14729.firebasestorage.app',
    measurementId: 'G-LMQQE219LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_jQ7ftRRFQBWAxGb8G-3s4JQcGKZeuY',
    appId: '1:779586378999:android:4a88a3cee983bc6ef787f2',
    messagingSenderId: '779586378999',
    projectId: 'fir-auth-14729',
    storageBucket: 'fir-auth-14729.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LqOIoLsEsOuvVwOeBBoGh-nYtvAWLgQ',
    appId: '1:779586378999:ios:be761afb2888466ef787f2',
    messagingSenderId: '779586378999',
    projectId: 'fir-auth-14729',
    storageBucket: 'fir-auth-14729.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LqOIoLsEsOuvVwOeBBoGh-nYtvAWLgQ',
    appId: '1:779586378999:ios:be761afb2888466ef787f2',
    messagingSenderId: '779586378999',
    projectId: 'fir-auth-14729',
    storageBucket: 'fir-auth-14729.firebasestorage.app',
    iosBundleId: 'com.example.myFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC22xk19-g75PRJ-tBwbzKiU_rBnCzxJec',
    appId: '1:779586378999:web:d05bcea76db0edd2f787f2',
    messagingSenderId: '779586378999',
    projectId: 'fir-auth-14729',
    authDomain: 'fir-auth-14729.firebaseapp.com',
    storageBucket: 'fir-auth-14729.firebasestorage.app',
    measurementId: 'G-PEN7WK5CM3',
  );
}